# Version of the configuration file
version: 3.0.0
# Path or URL to the website's logo / 显示在导航栏左侧的网站logo
logo: /img/logo.png #https://cdn.jsdelivr.net/gh/ji2xpro/ji2xpro.github.io@sourceCode/themes/amazing/source/img/logo.png

# Page metadata configurations
head:
    # URL or path to the website's icon / 你的网站图标，可以搜索在线图标制作，并将其放在img文件夹中
    favicon: /img/favicon.png
    # Canonical URL of the current page
    canonical_url:
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: Ji2xpro
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: https://ji2xpro.github.io/
        # Page cover (og:image) (optional) Default to the Open Graph image or thumbnail of the page
        # You should leave this blank for most of the time
        image: /img/avatar.png
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: Ji2xpro
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: ji2xpro
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: java，技术分享，后端开发，自动化框架，数据接口，算法，leetcode
        # Twitter card type (twitter:card)
        twitter_card:
        # Twitter ID (twitter:creator)
        twitter_id:
        # Twitter ID (twitter:creator)
        twitter_site:
        # Google+ profile link (deprecated)
        google_plus:
        # Facebook admin ID
        fb_admins:
        # Facebook App ID
        fb_app_id:
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: Ji2xpro
        # Page description (optional)
        # You should leave this blank for most of the time
        description: java，技术分享，后端开发，自动化框架，数据接口，算法，leetcode
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: https://ji2xpro.github.io/
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: ji2xpro
        # Page images (optional) Default to the Open Graph image or thumbnail of the page
        # You should leave this blank for most of the time
        image: /img/avatar.png
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: /atom.xml

# Page top navigation bar configurations / 导航栏设置
navbar:
    # Naviagtion menu items / 菜单（显示名称：对应文件夹）
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        影音: /media
        相册: /album
        友链: /friend
        碎碎念: /self-talking
        留言: /message
        关于: /about
    # Links to be shown on the right of the navigation bar / 导航栏右侧图标链接
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ji2xpro'

# Page footer configurations / 页面角标设置
footer:
    # Links to be shown on the right of the footer section / 页脚图标链接
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ji2xpro'

# Article related configurations / 文章显示设置
article:
    # Code highlight settings
    highlight:
        # Code highlight themes / 代码主题atom-one-light亮色，atom-one-dark暗色
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-dark
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show thumbnail image for every article / 是否显示文章主图
    thumbnail: true
    # Whether to show estimated article reading time / 是否显示估算阅读时间
    readtime: true

# Search plugin configurations / 搜索插件设置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight

# Donate plugin configurations / 打赏插件设置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donate:
    # Alipay donate button configurations / 阿里巴巴支付宝
    -
        # Donation entry name
        type: alipay
        # Qrcode image URL
        qrcode: 'https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190802135456.png'
    # Wechat donate button configurations / 微信
    -
        # Donation entry name
        type: wechat
        # Qrcode image URL
        qrcode: 'https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190802135550.png'
#    # patreon donate button configurations
#    -
#        type: patreon
#        # URL to the Patreon page
#        url: ''
#    # Paypal donate button configurations
#    -
#        type: paypal
#        # Paypal business ID or email address
#        business: ''
#        # Currency code
#        currency_code: USD

# Share plugin configurations / 分享插件设置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    # 插件类型，有多种，可选，自行百度
    type: sharejs
    # URL to the ShareThis share plugin script
    install_url: ''

# Sidebar configurations / 边栏设置
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations / 左侧边栏设置
    left:
        # Whether the sidebar sticks to the top when page scrolls / 是否不随页面滚动
        sticky: true
    # Right sidebar configurations / 右侧边栏设置
    right:
        # Whether the sidebar sticks to the top when page scrolls / 是否不随页面滚动
        sticky: false

# Sidebar widget configurations / 边栏挂件设置
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Table of contents widget configurations / 文章目录
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
    
    # Profile widget configurations / 个人信息
    -
        # Where should the widget be placed, left sidebar or right sidebar / 部件位置（左）
        position: left
        type: profile
        # Author name / 作者名称
        author: Ji2xpro
        # Title of the author to be shown in the profile widget / 作者头衔
        author_title: 尚未执佩剑，转眼即江湖
        # Author's current location to be shown in the profile widget / 作者所在地/公司
        location: 中国.上海
        # Path or URL to the avatar to be shown in the profile widget / 头像图片地址
        avatar: /img/avatar.png
        # Whether show the rounded avatar image / 是否显示圆形头像
        avatar_rounded: true
        # Email address for the Gravatar / Gravatar邮箱(如不设置`avatar`项) ps：如果你希望使用Gravatar而不是avatar配置项作为头像图片，请在gravatar项填入 你的Gravatar邮箱地址并在avatar一项中留空；
        gravatar:
        # URL or path for the follow button / 关注按钮链接地址
        follow_link: 'https://github.com/ji2xpro'
        # Links to be shown on the bottom of the profile widget / 社交媒体链接
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/ji2xpro'
            Weibo:
                icon: fab fa-weibo
                url: 'https://weibo.com/u/2521355870'
            Email:
                icon: fa fa-envelope
                url: 'mailto:ji2xpro@163.com'
            Next:
                icon: fab fa-dribbble
                url: 'https://removeif.github.io/remove.io'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
        has_hitokoto: true #左边一言开关，true-开，false-关
   
    # # Recommendation links widget configurations / 友站链接
    # -            
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     position: left
    #     type: links
    #     # Names and URLs of the sites / 友站名称与链接
    #     links:
    #         Hexo: 'https://hexo.io'
    #         Bulma: 'https://bulma.io'

    # latest comment widget configurations / 最新评论
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: latest_comment

    # Recent posts widget configurations / 最新文章
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts

    # Categories widget configurations / 文章分类
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: categories

    # Archives widget configurations / 文章归档
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives
    
    # Tags widget configurations / 文章标签
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: tags
    
    # Google FeedBurner email subscription widget configurations / 邮件订阅
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: subscribe_email
        # Hint text under the email input
        description: 输入邮箱开始订阅，更博后邮件通知！
        # Feedburner ID
        feedburner_id: ji2xproblog

    # # Google AdSense unit configurations
    # -
    #     # Where should the widget be placed, left sidebar or right sidebar
    #     position: left
    #     type: adsense
    #     # AdSense client ID
    #     client_id: ''
    #     # AdSense AD unit ID
    #     slot_id: ''

# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id:
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
    # # CNZZ statistics
    # # https://www.umeng.com/web
    # cnzz:
    #     # CNZZ tracker id
    #     id: 
    #     # CNZZ website id
    #     web_id: 
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id:
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id:
    # Enable the KaTeX math typesetting supprot
    # https://katex.org/
    katex: true
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Show a progress bar at top of the page on page loading
    progressbar: true

# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: loli
    # Name or URL template of the webfont CDN provider
    fontcdn: loli
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: loli
    # https://cdn.jsdelivr.net/gh/removeif/removeif.github.io@v1.0.6/json_data/record.json, cdn前缀，对于hexo new page 页面中引用的资源文件不生效，需要手动改，如friend友链页中引用的资源
    my_cdn_pre: #https://cdn.jsdelivr.net/gh/removeif/removeif.github.io@v2.2.1

# Comment plugin configurations / 评论插件设置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: gitalk
    language: zh-CN #zh-CN #Localization language key, en, zh-CN and zh-TW are currently available.
    owner: ji2xpro         # (required) GitHub user name
    repo: blog_comment          # (required) GitHub repository name
    client_id: 1290ff17595f9d44999f     # (required) OAuth application client id
    client_secret: 145d2a46ea42f48446ea6eb251cde00b1b88783f # (required) OAuth application client secret
    admin: ['ji2xpro']
    create_issue_manually: true
    distraction_free_mode: false
    has_hot_recommend: true # 是否有热门推荐
    has_latest_comment: true #是否有最新评论

# comment:
#     type: valine
#     app_id: rOtVIhvG3kd7QkMKe3naSU9R-gzGzoHsz
#     app_key: F2sNV0CkqvbPat45di3DEn3z
#     notify: false
#     verify: false
#     avatar: 'mp'
#     placeholder: '留下您的高见！'
#     has_latest_comment: true #是否有最新评论 true-有，false-无
#     owner: 辣椒の酱 #博主名 最新评论标注[博主]
#     required_fields: ['nick', 'mail', 'link']
#     lang: en #zh-CN zh-TW en ja


# utteranc site: https://utteranc.es/
# comment:
#     type: utteranc
#     repo: removeif/utteranc_comment # (required) GitHub userName & repository name
#     issue_term: pathname 
#     issue_number: 
#     label: 
#     theme: github-light
  
global_gray: false #true 全局灰色，特定时期可以开启，false-不开启

has_banner: false #首页是否有banner，true-是，false-否，如果配置了热门推荐显示热门推荐，banner配置数据在json_data/banner.json里按照配置格式配置好，至少三条

has_latest_modify_time: true #是否显示最后修改时间 true开启，false-关闭   

busuanzi_only_count: false #当上面plugins中busuanzi: true时，此配置busuanzi_only_count为true时，网站不显示不蒜子统计数据，但是会每次统计。false时显示统计数据。

has_copyright: true # 文中是否显示copyright true开启，false-关闭   

# http://sachinchoolur.github.io/lightGallery/docs/api.html 
lightgallery_is_full: true #图片灯箱是否显示完整的插件(包括放大，分享等)，true-显示，false-显示简洁版

website_start_time: 2020/01/01 00:00:00 #网站运行开始时间,不填不显示

footer_registered_no: #川ICP备88888888号-8 #备案号

footer_copyright_dsec: © 版权说明：[本网站所有内容均收集于互联网或自己创作,<br />&nbsp;&nbsp;&nbsp;&nbsp;方便于网友与自己学习交流，如有侵权，请<a href="/message" target="_blank">留言</a>，立即处理]<br /> #footer 版权说明 可自由配置

has_live_2D_switch: true #live2D开关 true-开 false-关

side_music_netease_id: 2364053447 #侧边栏网易云歌单id

use_pjax: false #是否开启pjax，false-不开启，true-开启，开启后局部更新网页信息，切换页面背景音乐不间断等特性

index_show_tags_cateories: true #首页文章item面板是否显示tag和categories